// Single inventory for the website, Sheets and the admin editor.
export const contentFields = [
  {"key":"home_title","value":"Epa","group":"home","limit":200},
  {"key":"home_subtitle","value":"La teva botiga de dietètica de barri.","group":"home","limit":500},
  {"key":"home_text","value":"Un espai proper per cuidar-te cada dia. A La Circular volem acompanyar-te amb una atenció personal i una selecció de productes per al teu benestar.","group":"home","limit":10000},
  {"key":"project_title","value":"El nostre projecte.","group":"project","limit":200},
  {"key":"project_content","value":"La Circular neix amb la idea de ser una botiga de dietètica propera, arrelada al barri i a les persones que en formen part. Creiem en un tracte de tu a tu, en escoltar i en ajudar-te a trobar opcions que encaixin amb el teu dia a dia.","group":"project","limit":20000},
  {"key":"products_title","value":"Productes.","group":"products","limit":200},
  {"key":"products_intro","value":"Alimentació, infusions, suplements i cura personal. Descobreix la selecció de La Circular per al teu dia a dia.","group":"products","limit":2000},
  {"key":"home_cuidar_nos_de_manera_natural","value":"Cuidar-nos.\nDe manera\nnatural.","group":"home","limit":2000},
  {"key":"home_benestar_amb_proximitat","value":"Benestar, amb proximitat","group":"home","limit":2000},
  {"key":"home_descobreix_els_productes","value":"Descobreix els productes","group":"home","limit":2000},
  {"key":"home_text_2","value":"↗","group":"home","limit":2000},
  {"key":"home_el_nostre_projecte","value":"El nostre projecte","group":"home","limit":2000},
  {"key":"home_text_3","value":"→","group":"home","limit":2000},
  {"key":"home_la_circular","value":"LA CIRCULAR","group":"home","limit":2000},
  {"key":"home_a_prop_teu","value":"A PROP TEU","group":"home","limit":2000},
  {"key":"home_les_petites_coses_de_cada_dia","value":"Les petites coses de cada dia.","group":"home","limit":2000},
  {"key":"home_la_nostra_manera_de_fer","value":"La nostra manera de fer","group":"home","limit":2000},
  {"key":"home_les_persones_al_centre","value":"Les persones, al centre.","group":"home","limit":2000},
  {"key":"home_01","value":"01 /","group":"home","limit":2000},
  {"key":"home_a_prop_teu_2","value":"A prop teu","group":"home","limit":2000},
  {"key":"home_una_botiga_de_barri_amb_temps_per","value":"Una botiga de barri, amb temps per escoltar-te i un tracte de tu a tu.","group":"home","limit":2000},
  {"key":"home_02","value":"02 /","group":"home","limit":2000},
  {"key":"home_cuidar_el_dia_a_dia","value":"Cuidar el dia a dia","group":"home","limit":2000},
  {"key":"home_opcions_d_alimentacio_i_cura_personal_que","value":"Opcions d’alimentació i cura personal que encaixen amb la teva vida.","group":"home","limit":2000},
  {"key":"home_03","value":"03 /","group":"home","limit":2000},
  {"key":"home_triar_amb_calma","value":"Triar amb calma","group":"home","limit":2000},
  {"key":"home_un_espai_on_compartir_dubtes_i_descobrir","value":"Un espai on compartir dubtes i descobrir allò que necessites.","group":"home","limit":2000},
  {"key":"project_petits_gestos_benestar_quotidia","value":"Petits gestos.\nBenestar quotidià.","group":"project","limit":2000},
  {"key":"project_la_nostra_filosofia","value":"La nostra filosofia","group":"project","limit":2000},
  {"key":"project_arrelats_al_barri","value":"Arrelats al barri","group":"project","limit":2000},
  {"key":"project_un_espai_proper_una_manera_de_cuidar","value":"Un espai proper. Una manera de cuidar-nos.","group":"project","limit":2000},
  {"key":"project_descobreix_els_nostres_productes","value":"Descobreix els nostres productes","group":"project","limit":2000},
  {"key":"project_ens_agrada_fer_les_coses_amb_calma","value":"Ens agrada fer les coses amb calma, amb cura i amb proximitat.","group":"project","limit":2000},
  {"key":"products_no_hem_trobat_cap_producte","value":"No hem trobat cap producte","group":"products","limit":2000},
  {"key":"products_encara_no_hi_ha_productes_disponibles","value":"Encara no hi ha productes disponibles","group":"products","limit":2000},
  {"key":"products_prova_amb_un_altre_nom_o_categoria","value":"Prova amb un altre nom o categoria, o neteja els filtres.","group":"products","limit":2000},
  {"key":"products_torna_a_visitar_el_cataleg_mes_endavant","value":"Torna a visitar el catàleg més endavant.","group":"products","limit":2000},
  {"key":"products_cerca_al_cataleg","value":"Cerca al catàleg","group":"products","limit":2000},
  {"key":"products_per_exemple_camamilla","value":"Per exemple, camamilla","group":"products","limit":2000},
  {"key":"products_productes","value":"Productes","group":"products","limit":2000},
  {"key":"products_la_nostra_seleccio","value":"La nostra selecció","group":"products","limit":2000},
  {"key":"products_carregant_els_productes","value":"Carregant els productes…","group":"products","limit":2000},
  {"key":"products_no_hem_pogut_carregar_el_cataleg","value":"No hem pogut carregar el catàleg","group":"products","limit":2000},
  {"key":"products_torna_ho_a_provar_d_aqui_a","value":"Torna-ho a provar d’aquí a uns instants.","group":"products","limit":2000},
  {"key":"products_torna_ho_a_provar","value":"Torna-ho a provar","group":"products","limit":2000},
  {"key":"products_cerca_per_nom","value":"Cerca per nom","group":"products","limit":2000},
  {"key":"products_categoria","value":"Categoria","group":"products","limit":2000},
  {"key":"products_totes_les_categories","value":"Totes les categories","group":"products","limit":2000},
  {"key":"products_neteja_els_filtres","value":"Neteja els filtres","group":"products","limit":2000},
  {"key":"header_menu","value":"Menú","group":"header","limit":2000},
  {"key":"header_la_circular_inici","value":"La Circular — Inici","group":"header","limit":2000},
  {"key":"header_navegacio_principal","value":"Navegació principal","group":"header","limit":2000},
  {"key":"header_la_circular","value":"La Circular","group":"header","limit":2000},
  {"key":"header_dietetica_de_barri","value":"DIETÈTICA DE BARRI","group":"header","limit":2000},
  {"key":"header_inici","value":"Inici","group":"header","limit":2000},
  {"key":"footer_text","value":".","group":"footer","limit":2000},
  {"key":"footer_a_prop_teu_cada_dia","value":"A prop teu, cada dia.","group":"footer","limit":2000},
  {"key":"common_carregant_els_textos","value":"Carregant els textos…","group":"common","limit":2000},
  {"key":"common_no_hem_pogut_carregar_els_textos_torna","value":"No hem pogut carregar els textos. Torna-ho a provar d’aquí a uns instants.","group":"common","limit":2000},
  {"key":"common_torna_a_carregar_els_textos","value":"Torna a carregar els textos","group":"common","limit":2000},
  {"key":"common_carregant_els_continguts","value":"Carregant els continguts…","group":"common","limit":2000},
  {"key":"common_salta_al_contingut","value":"Salta al contingut","group":"common","limit":2000},
  {"key":"admin_tens_canvis_sense_desar_vols_tancar_la","value":"Tens canvis sense desar. Vols tancar la sessió igualment?","group":"admin","limit":2000},
  {"key":"admin_administracio_la_circular","value":"Administració · La Circular","group":"admin","limit":2000},
  {"key":"admin_les_contrasenyes_no_coincideixen","value":"Les contrasenyes no coincideixen.","group":"admin","limit":2000},
  {"key":"admin_tancant_la_sessio","value":"Tancant la sessió…","group":"admin","limit":2000},
  {"key":"admin_tanca_la_sessio","value":"Tanca la sessió","group":"admin","limit":2000},
  {"key":"admin_activa_el_teu_acces_amb_una_contrasenya","value":"Activa el teu accés amb una contrasenya.","group":"admin","limit":2000},
  {"key":"admin_acces_reservat_a_les_persones_convidades","value":"Accés reservat a les persones convidades.","group":"admin","limit":2000},
  {"key":"admin_crea_una_contrasenya","value":"Crea una contrasenya","group":"admin","limit":2000},
  {"key":"admin_un_moment","value":"Un moment…","group":"admin","limit":2000},
  {"key":"admin_activa_l_acces","value":"Activa l'accés","group":"admin","limit":2000},
  {"key":"admin_inicia_la_sessio","value":"Inicia la sessió","group":"admin","limit":2000},
  {"key":"admin_administracio","value":"Administració","group":"admin","limit":2000},
  {"key":"admin_comprovant_l_acces","value":"Comprovant l'accés…","group":"admin","limit":2000},
  {"key":"admin_sessio_iniciada","value":"Sessió iniciada","group":"admin","limit":2000},
  {"key":"admin_benvingut_a_l_espai_d_administracio_de","value":"Benvingut a l'espai d'administració de La Circular.","group":"admin","limit":2000},
  {"key":"admin_correu_electronic","value":"Correu electrònic","group":"admin","limit":2000},
  {"key":"admin_fes_servir_almenys_8_caracters","value":"Fes servir almenys 8 caràcters.","group":"admin","limit":2000},
  {"key":"admin_repeteix_la_contrasenya","value":"Repeteix la contrasenya","group":"admin","limit":2000},
  {"key":"admin_torna_a_la_web","value":"Torna a la web","group":"admin","limit":2000},
  {"key":"admin_la_sessio_ha_caducat_copia_els_canvis","value":"La sessió ha caducat. Copia els canvis abans de tornar a iniciar la sessió.","group":"admin","limit":2000},
  {"key":"admin_no_s_ha_autoritzat_la_peticio_torna","value":"No s’ha autoritzat la petició. Torna a obrir el panell des de la web.","group":"admin","limit":2000},
  {"key":"admin_la_peticio_es_massa_gran_redueix_la","value":"La petició és massa gran. Redueix la mida dels textos i torna-ho a provar.","group":"admin","limit":2000},
  {"key":"admin_no_hem_pogut_llegir_la_peticio_de","value":"No hem pogut llegir la petició de guardat. Copia els canvis, recarrega el panell i torna-ho a provar.","group":"admin","limit":2000},
  {"key":"admin_revisa_que_tots_els_camps_continguin_text","value":"Revisa que tots els camps continguin text i respectin el límit de caràcters.","group":"admin","limit":2000},
  {"key":"admin_no_hem_pogut_confirmar_que_els_canvis","value":"No hem pogut confirmar que els canvis s’hagin desat. Els textos es conserven aquí perquè puguis tornar-ho a provar.","group":"admin","limit":2000},
  {"key":"admin_no_hem_pogut_carregar_els_textos_torna","value":"No hem pogut carregar els textos. Torna-ho a provar.","group":"admin","limit":2000},
  {"key":"admin_omple_tots_els_camps_amb_text_i","value":"Omple tots els camps amb text i respecta el límit de caràcters.","group":"admin","limit":2000},
  {"key":"admin_tens_canvis_sense_desar_vols_sortir_igualment","value":"Tens canvis sense desar. Vols sortir igualment?","group":"admin","limit":2000},
  {"key":"admin_desant","value":"Desant…","group":"admin","limit":2000},
  {"key":"admin_desa_els_canvis","value":"Desa els canvis","group":"admin","limit":2000},
  {"key":"admin_canvis_desats_ja_es_poden_veure_a","value":"Canvis desats. Ja es poden veure a la web.","group":"admin","limit":2000},
  {"key":"admin_tens_canvis_sense_desar","value":"Tens canvis sense desar.","group":"admin","limit":2000},
  {"key":"admin_textos_de_la_web","value":"Textos de la web","group":"admin","limit":2000},
  {"key":"admin_edita_els_textos_i_desa_els_canvis","value":"Edita els textos i desa els canvis per publicar-los. Pots separar els paràgrafs amb salts de línia.","group":"admin","limit":2000},
  {"key":"admin_veure_la_pagina","value":"Veure la pàgina","group":"admin","limit":2000},
  {"key":"admin_s_obre_en_una_pestanya_nova","value":"(s’obre en una pestanya nova)","group":"admin","limit":2000},
  {"key":"admin_no_hem_pogut_carregar_els_productes_torna","value":"No hem pogut carregar els productes. Torna-ho a provar.","group":"admin","limit":2000},
  {"key":"admin_imatge_desada_i_associada_al_producte","value":"Imatge desada i associada al producte.","group":"admin","limit":2000},
  {"key":"admin_la_imatge_supera_el_limit_de_5","value":"La imatge supera el límit de 5 MB.","group":"admin","limit":2000},
  {"key":"admin_fes_servir_una_imatge_jpg_png_o","value":"Fes servir una imatge JPG, PNG o WebP.","group":"admin","limit":2000},
  {"key":"admin_no_hem_pogut_desar_la_imatge_comprova","value":"No hem pogut desar la imatge. Comprova la sessió i torna-ho a provar.","group":"admin","limit":2000},
  {"key":"admin_vols_eliminar_la_imatge_d_aquest_producte","value":"Vols eliminar la imatge d’aquest producte?","group":"admin","limit":2000},
  {"key":"admin_imatge_eliminada_del_producte","value":"Imatge eliminada del producte.","group":"admin","limit":2000},
  {"key":"admin_no_hem_pogut_eliminar_la_imatge_torna","value":"No hem pogut eliminar la imatge. Torna-ho a provar.","group":"admin","limit":2000},
  {"key":"admin_canvia_la_imatge","value":"Canvia la imatge","group":"admin","limit":2000},
  {"key":"admin_afegeix_la_imatge","value":"Afegeix la imatge","group":"admin","limit":2000},
  {"key":"admin_imatges_dels_productes","value":"Imatges dels productes","group":"admin","limit":2000},
  {"key":"admin_producte","value":"Producte","group":"admin","limit":2000},
  {"key":"admin_aquest_producte_encara_no_te_imatge","value":"Aquest producte encara no té imatge.","group":"admin","limit":2000},
  {"key":"admin_selecciona_una_imatge","value":"Selecciona una imatge","group":"admin","limit":2000},
  {"key":"admin_jpg_png_o_webp_maxim_5_mb","value":"JPG, PNG o WebP · màxim 5 MB","group":"admin","limit":2000},
  {"key":"admin_elimina_la_imatge","value":"Elimina la imatge","group":"admin","limit":2000},
  {"key":"editor_group_home","value":"Inici","group":"admin","limit":200},
  {"key":"editor_group_project","value":"El nostre projecte","group":"admin","limit":200},
  {"key":"editor_group_products","value":"Productes","group":"admin","limit":200},
  {"key":"editor_group_header","value":"Capçalera","group":"admin","limit":200},
  {"key":"editor_group_footer","value":"Peu de pàgina","group":"admin","limit":200},
  {"key":"editor_group_common","value":"Accessibilitat i missatges","group":"admin","limit":200},
  {"key":"editor_group_admin","value":"Administració","group":"admin","limit":200},
  {"key":"editor_limit","value":"Màxim {limit} caràcters.","group":"admin","limit":2000},
  {"key":"products_count_one","value":"{count} producte","group":"products","limit":2000},
  {"key":"products_count_many","value":"{count} productes","group":"products","limit":2000},
  {"key":"products_count_filtered_one","value":"{count} producte de {total}","group":"products","limit":2000},
  {"key":"products_count_filtered_many","value":"{count} productes de {total}","group":"products","limit":2000},
  {"key":"products_image_alt","value":"Imatge de {name}","group":"products","limit":2000},
  {"key":"admin_image_alt","value":"Imatge actual de {name}","group":"admin","limit":2000},
  {"key":"site_title","value":"La Circular","group":"common","limit":2000},
  {"key":"admin_password","value":"Contrasenya","group":"admin","limit":2000},
  {"key":"header_close_menu","value":"Tanca","group":"header","limit":2000},
  {"key":"admin_auth_message_1","value":"L'accés d'administració encara no està configurat.","group":"admin","limit":2000},
  {"key":"admin_auth_message_2","value":"No hem pogut comprovar la sessió. Torna-ho a provar.","group":"admin","limit":2000},
  {"key":"admin_auth_message_3","value":"No podem connectar amb el servei d'accés. Torna-ho a provar més tard.","group":"admin","limit":2000},
  {"key":"admin_auth_message_4","value":"No hem pogut iniciar la sessió. Comprova el correu i la contrasenya i torna-ho a provar.","group":"admin","limit":2000},
  {"key":"admin_auth_message_5","value":"No hem pogut activar l'accés. Comprova la contrasenya o demana una nova invitació.","group":"admin","limit":2000},
  {"key":"admin_auth_message_6","value":"No hem pogut tancar la sessió. Torna-ho a provar.","group":"admin","limit":2000},
  {"key":"admin_product_option","value":"{name} · {category}","group":"admin","limit":2000},
  {"key":"admin_product_option_inactive","value":"{name} · {category} · Inactiu","group":"admin","limit":2000},
] as const

export const legacyContentKeys = ["home_title","home_subtitle","home_text","project_title","project_content","products_title","products_intro"] as const
export type ContentKey = (typeof contentFields)[number]['key']
export type SiteContent = Record<ContentKey, string>
export const contentKeys = contentFields.map(field => field.key)
export const defaultSiteContent = Object.fromEntries(contentFields.map(field => [field.key, field.value])) as SiteContent
